In [4]:
import pandas as pd
import numpy as np
import glob
import os

In [5]:
path = os.getcwd()
csv_files = glob.glob(os.path.join("data/car/", "*.csv"))

csv_files

['data/car/vauxhall.csv',
 'data/car/bmw.csv',
 'data/car/vw.csv',
 'data/car/hyundi.csv',
 'data/car/audi.csv',
 'data/car/toyota.csv',
 'data/car/ford.csv',
 'data/car/focus.csv',
 'data/car/skoda.csv',
 'data/car/cclass.csv',
 'data/car/merc.csv']

In [6]:
car_data = []
for file_name in csv_files:
    data = pd.read_csv(file_name)
    if file_name[9:-4] == 'cclass':
        data['brand'] = 'merc'
    else:
        data['brand'] = f'{file_name[9:-4]}'
    car_data.append(data)

In [7]:
car_data = pd.concat(car_data, ignore_index=True)

In [8]:
car_data

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,brand
0,Corsa,2018,7885,Manual,9876,Petrol,145.0,55.4,1.4,vauxhall
1,Corsa,2019,11995,Manual,2500,Petrol,145.0,54.3,1.4,vauxhall
2,Corsa,2017,9777,Automatic,9625,Petrol,145.0,47.9,1.4,vauxhall
3,Corsa,2016,8500,Manual,25796,Petrol,30.0,55.4,1.4,vauxhall
4,Corsa,2019,10000,Manual,3887,Petrol,145.0,43.5,1.4,vauxhall
...,...,...,...,...,...,...,...,...,...,...
108535,C Class,2020,35999,Automatic,500,Diesel,145.0,55.4,2.0,merc
108536,B Class,2020,24699,Automatic,2500,Diesel,145.0,55.4,2.0,merc
108537,GLC Class,2019,30999,Automatic,11612,Diesel,145.0,41.5,2.1,merc
108538,CLS Class,2019,37990,Automatic,2426,Diesel,145.0,45.6,2.0,merc
108539,S Class,2019,54999,Automatic,2075,Diesel,145.0,52.3,2.9,merc

In [9]:
car_data['name'] = car_data['brand']+" "+car_data['model']

In [10]:
car_data

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,brand,name
0,Corsa,2018,7885,Manual,9876,Petrol,145.0,55.4,1.4,vauxhall,vauxhall Corsa
1,Corsa,2019,11995,Manual,2500,Petrol,145.0,54.3,1.4,vauxhall,vauxhall Corsa
2,Corsa,2017,9777,Automatic,9625,Petrol,145.0,47.9,1.4,vauxhall,vauxhall Corsa
3,Corsa,2016,8500,Manual,25796,Petrol,30.0,55.4,1.4,vauxhall,vauxhall Corsa
4,Corsa,2019,10000,Manual,3887,Petrol,145.0,43.5,1.4,vauxhall,vauxhall Corsa
...,...,...,...,...,...,...,...,...,...,...,...
108535,C Class,2020,35999,Automatic,500,Diesel,145.0,55.4,2.0,merc,merc C Class
108536,B Class,2020,24699,Automatic,2500,Diesel,145.0,55.4,2.0,merc,merc B Class
108537,GLC Class,2019,30999,Automatic,11612,Diesel,145.0,41.5,2.1,merc,merc GLC Class
108538,CLS Class,2019,37990,Automatic,2426,Diesel,145.0,45.6,2.0,merc,merc CLS Class
108539,S Class,2019,54999,Automatic,2075,Diesel,145.0,52.3,2.9,merc,merc S Class

In [11]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108540 entries, 0 to 108539
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   model         108540 non-null  object
 1   year          108540 non-null  int64
 2   price         108540 non-null  int64
 3   transmission  108540 non-null  object
 4   mileage       108540 non-null  int64
 5   fuelType      108540 non-null  object
 6   tax           99187 non-null   float64
 7   mpg           99187 non-null   float64
 8   engineSize    108540 non-null  float64
 9   brand         108540 non-null  object
 10  name          108540 non-null  object
dtypes: float64(3), int64(3), object(5)
memory usage: 9.1+ MB

In [12]:
car_data.isnull().sum()

model              0
year               0
price              0
transmission       0
mileage            0
fuelType           0
tax             9353
mpg             9353
engineSize         0
brand              0
name               0
dtype: int64

In [13]:
car_data.dropna(inplace=True)

In [14]:
car_data.duplicated().sum()

1475

In [15]:
car_data.drop_duplicates(inplace=True)

In [16]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 97712 entries, 0 to 108539
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         97712 non-null  object
 1   year          97712 non-null  int64
 2   price         97712 non-null  int64
 3   transmission  97712 non-null  object
 4   mileage       97712 non-null  int64
 5   fuelType      97712 non-null  object
 6   tax           97712 non-null  float64
 7   mpg           97712 non-null  float64
 8   engineSize    97712 non-null  float64
 9   brand         97712 non-null  object
 10  name          97712 non-null  object
dtypes: float64(3), int64(3), object(5)
memory usage: 8.9+ MB

In [17]:
car_data

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,brand,name
0,Corsa,2018,7885,Manual,9876,Petrol,145.0,55.4,1.4,vauxhall,vauxhall Corsa
1,Corsa,2019,11995,Manual,2500,Petrol,145.0,54.3,1.4,vauxhall,vauxhall Corsa
2,Corsa,2017,9777,Automatic,9625,Petrol,145.0,47.9,1.4,vauxhall,vauxhall Corsa
3,Corsa,2016,8500,Manual,25796,Petrol,30.0,55.4,1.4,vauxhall,vauxhall Corsa
4,Corsa,2019,10000,Manual,3887,Petrol,145.0,43.5,1.4,vauxhall,vauxhall Corsa
...,...,...,...,...,...,...,...,...,...,...,...
108535,C Class,2020,35999,Automatic,500,Diesel,145.0,55.4,2.0,merc,merc C Class
108536,B Class,2020,24699,Automatic,2500,Diesel,145.0,55.4,2.0,merc,merc B Class
108537,GLC Class,2019,30999,Automatic,11612,Diesel,145.0,41.5,2.1,merc,merc GLC Class
108538,CLS Class,2019,37990,Automatic,2426,Diesel,145.0,45.6,2.0,merc,merc CLS Class
108539,S Class,2019,54999,Automatic,2075,Diesel,145.0,52.3,2.9,merc,merc S Class

In [18]:
car_data['description'] = car_data['year'].map(str)+car_data['transmission']+car_data['engineSize'].map(str)+car_data['fuelType']+car_data['mpg'].map(str)+car_data['mileage'].map(str)

In [19]:
car_data

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,brand,name,description
0,Corsa,2018,7885,Manual,9876,Petrol,145.0,55.4,1.4,vauxhall,vauxhall Corsa,2018Manual1.4Petrol55.49876
1,Corsa,2019,11995,Manual,2500,Petrol,145.0,54.3,1.4,vauxhall,vauxhall Corsa,2019Manual1.4Petrol54.32500
2,Corsa,2017,9777,Automatic,9625,Petrol,145.0,47.9,1.4,vauxhall,vauxhall Corsa,2017Automatic1.4Petrol47.99625
3,Corsa,2016,8500,Manual,25796,Petrol,30.0,55.4,1.4,vauxhall,vauxhall Corsa,2016Manual1.4Petrol55.425796
4,Corsa,2019,10000,Manual,3887,Petrol,145.0,43.5,1.4,vauxhall,vauxhall Corsa,2019Manual1.4Petrol43.53887
...,...,...,...,...,...,...,...,...,...,...,...,...
108535,C Class,2020,35999,Automatic,500,Diesel,145.0,55.4,2.0,merc,merc C Class,2020Automatic2.0Diesel55.4500
108536,B Class,2020,24699,Automatic,2500,Diesel,145.0,55.4,2.0,merc,merc B Class,2020Automatic2.0Diesel55.42500
108537,GLC Class,2019,30999,Automatic,11612,Diesel,145.0,41.5,2.1,merc,merc GLC Class,2019Automatic2.1Diesel41.511612
108538,CLS Class,2019,37990,Automatic,2426,Diesel,145.0,45.6,2.0,merc,merc CLS Class,2019Automatic2.0Diesel45.62426
108539,S Class,2019,54999,Automatic,2075,Diesel,145.0,52.3,2.9,merc,merc S Class,2019Automatic2.9Diesel52.32075

In [20]:
car_data['description'][0]

'2018Manual1.4Petrol55.49876'

In [21]:
car_data['description'] = car_data['description'].apply(lambda x:x.lower())
car_data['name'] = car_data['name'].apply(lambda x:x.lower())

In [22]:
car_data = car_data[['name','description']]

In [23]:
car_data.head()

              name                     description
0  vauxhall  corsa     2018manual1.4petrol55.49876
1  vauxhall  corsa     2019manual1.4petrol54.32500
2  vauxhall  corsa  2017automatic1.4petrol47.99625
3  vauxhall  corsa    2016manual1.4petrol55.425796
4  vauxhall  corsa     2019manual1.4petrol43.53887

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=100000, stop_words='english')

In [25]:
cv.fit_transform(car_data['description']).toarray().shape

(97712, 77226)

In [26]:
vectors = cv.fit_transform(car_data['description']).toarray()

In [27]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [28]:
len(cv.get_feature_names_out())

77226

In [29]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [30]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
cosine_similarity(vectors)